{"name": "报价测试", "status": "broken", "statusDetails": {"message": "TypeError: fill_in_from() got an unexpected keyword argument 'time'", "trace": "self = <test_case.dev_case.quotation.test_kaishisong_dev_quotation.TestKaiShiSong object at 0x109dadb20>\nfrom_data = {'from_address': '12栋', 'item_select': '文件票证', 'remarke': '', 'time': '今天 立即取件', ...}\n\n    @allure.title(\"报价测试\")\n    @pytest.mark.parametrize('from_data', yaml.safe_load(open('../../../test_data/from_data.yaml', 'r')))\n    def test_quotation(self, from_data: dict):\n    \n>       self.main.fill_in_from(from_data.get('from_address'), from_data.get('to_address'),\n                               item_select=from_data.get('item_select'), time=from_data.get('time'),\n                               weight=from_data.get(\"weight\"))\nE       TypeError: fill_in_from() got an unexpected keyword argument 'time'\n\ntest_kaishisong_dev_quotation.py:29: TypeError"}, "attachments": [{"name": "log", "source": "6745de1e-7a48-4fd6-8e6f-869b8f55c403-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "from_data", "value": "{'from_address': '12栋', 'to_address': '完美世界', 'wegiht': '5', 'item_select': '文件票证', 'remarke': '', 'time': '今天 立即取件'}"}], "start": 1622883131105, "stop": 1622883131106, "uuid": "2d84b431-71cd-49f3-934f-101d5c091eab", "historyId": "484acb34c77d4b6ed9cbff0558d214db", "testCaseId": "321955b6535e91700bb31f820357e448", "fullName": "test_case.dev_case.quotation.test_kaishisong_dev_quotation.TestKaiShiSong#test_quotation", "labels": [{"name": "parentSuite", "value": "test_case.dev_case.quotation"}, {"name": "suite", "value": "test_kaishisong_dev_quotation"}, {"name": "subSuite", "value": "TestKaiShiSong"}, {"name": "host", "value": "macdeMBP"}, {"name": "thread", "value": "28864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.dev_case.quotation.test_kaishisong_dev_quotation"}]}